### ISSUE TITLE
Using `whoami` without authenticating displays an error message

### ISSUE THREAD

**Issue by markvincze** [Travix-International/Travix.Core.Adk#23]
If we install appix and issue the `whoami` command without authenticating first, it displays the following error:

```
2016/11/25 09:28:46 Failed to read auth file C:\Users\mvincze.DEV\.appix\auth.json
2016/11/25 09:28:46 open C:\Users\mvincze.DEV\.appix\auth.json: The system cannot find the file specified.
```

Instead it should display a message telling the user they're not authenticated, and they can log in with `appix login`.

cc @fahad19

**Comment by alexmiranda** [comment]
Fixed by [PR-28](https://github.com/Travix-International/Travix.Core.Adk/pull/28)
